src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phonenumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $postalcode = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'seller', targetEntity: Product::class)]
    private Collection $products;

    #[ORM\ManyToMany(targetEntity: Product::class, inversedBy: 'users')]
    private Collection $favorites;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Cart $cart = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->products = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullname(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhonenumber(): ?string
    {
        return $this->phonenumber;
    }

    public function setPhonenumber(?string $phonenumber): self
    {
        $this->phonenumber = $phonenumber;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalcode(): ?string
    {
        return $this->postalcode;
    }

    public function setPostalcode(?string $postalcode): self
    {
        $this->postalcode = $postalcode;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setSeller($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getSeller() === $this) {
                $product->setSeller(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Product $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites->add($favorite);
        }

        return $this;
    }

    public function removeFavorite(Product $favorite): self
    {
        $this->favorites->removeElement($favorite);

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        // unset the owning side of the relation if necessary
        if ($cart === null && $this->cart !== null) {
            $this->cart->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($cart !== null && $cart->getUser() !== $this) {
            $cart->setUser($this);
        }

        $this->cart = $cart;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

src/Controller/ContentController.php
<?php

namespace App\Controller;

use App\Entity\CartsProducts;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProductRepository;
use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\CartsProductsRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Form\AddCartType;
use App\Repository\BrandRepository;
use App\Repository\CategoryRepository;
use App\Entity\User;
use App\Form\CartQuantityType;

class ContentController extends AbstractController
{
    #[Route('/', name: 'app_product_home')]
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('content/home.html.twig', [
            'controller_name' => 'ContentController',
            'products' => $productRepository->findBy([], ['sold' => 'DESC'], 3),
            'productz' => $productRepository->findBy(array('brand' => 3),array('id'=>'DESC'),3),
        ]);
    }

    #[Route('/{id}/cart', name: 'app_product_cart', methods: ['GET', 'POST'])]
    public function cart(User $user, Request $request, CartsProductsRepository $cartProducts): Response
    {
        $cart = $user->getCart();
        $cp = $cart->getCartsProducts();
        $cparray = $cp->toArray();
        $quantities = [];
        foreach ($cparray as $cartsProducts) {
            array_push($quantities, $cartsProducts->getQuantity() * $cartsProducts->getProduct()->getPrice());
        }

        $totalPrice = array_sum($quantities);
        return $this->render('content/cart.html.twig', [
            'controller_name' => 'ContentController',
            'products' => $cp,
            'quantities' => $quantities,
            'totalPrice' => $totalPrice,
        ]);
    }

    #[Route('/cart/update/', name: 'app_product_cart_update', methods: ['GET', 'POST'])]
    public function updatecart(CartsProductsRepository $cartProducts, Request $request, ProductRepository $productRepository): Response {
        $test = $request->getContent();
        $data = json_decode($test, true);
        $cp = $cartProducts->find($data['id']);
        $cp->setQuantity($data['quantity']);
        $cartProducts->save($cp, true);


        return $this->redirectToRoute('app_product_home');
    }

    #[Route('/admin', name: 'app_product_admin')]
    public function admin(): Response
    {
        return $this->render('content/product/index.html.twig', [
            'controller_name' => 'ContentController',
        ]);
    }

    #[Route('/admin/product', name: 'app_products', methods: ['GET'])]
    public function showAll(ProductRepository $productRepository): Response
    {
        return $this->render('content/product/adminproduct.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    #[Route('/shop', name: 'app_shop', methods: ['GET'])]
    public function showAllShop(ProductRepository $productRepository, PaginatorInterface $paginator, Request $request): Response
    {
        return $this->render('content/shop.html.twig', [
            'products' => $paginator->paginate($productRepository->findAll(),
            $request->query->getInt('page', 1),9
        ),
        ]);
    }

    #[Route('/products/{id}', name: 'app_product_read', methods: ['GET', 'POST'])]
    public function show(Product $product, Request $request, CartsProductsRepository $cpRepository): Response
    {
        /** @var User $user **/
        $user = $this->getUser();
        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $cart = $user->getCart();
        $cartProduct = new CartsProducts();
        $form = $this->createForm(AddCartType::class, $cartProduct);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $cartProduct->setCart($cart);
            $cartProduct->setProduct($product);
            $quantity = $form->get('quantity')->getData();
            $cartProduct->setQuantity($quantity);

            $cpRepository->save($cartProduct, true);

            return $this->redirectToRoute('app_products');
        }
        return $this->render('content/product/show.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/profile', name: 'app_profile', methods: ['GET'])]
    public function profile(ProductRepository $productRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $user = $this->getUser()->getId();
        return $this->render('content/profile.html.twig', [
            'products' => $paginator->paginate($productRepository->findBy(['seller' => $user]), $request->query->getInt('page', 1),2),
        ]);
    }
}

templates/content/_delete_cartproduct_form.html.twig
<form method="post" action="{{ path('app_carts_products_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class=" btn btn-warning">Delete</button>
</form>

templates/content/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.description) }}
    {{ form_row(form.image) }}
    {{ form_row(form.quantity) }}
    {{ form_row(form.sold) }}
    {{ form_row(form.price) }}
    {{ form_row(form.statut) }}
    {% if is_granted ('ROLE_ADMIN') %}
    {{ form_row(form.seller) }}
    {% endif %}
    {{ form_row(form.category) }}
    {{ form_row(form.brand)}}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/content/_paginator.html.twig
{#
/**
 * @file
 * Bootstrap v5 Sliding pagination control implementation.
 *
 * View that can be used with the pagination module
 * from the Bootstrap CSS Framework
 * https://getbootstrap.com/docs/5.0/components/pagination/
 */
#}
{% extends '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' %}

templates/content/cart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart{% endblock %}

{% block body %}
    <section class="h-100" style="background-color: #eee;">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">

        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
        </div>

        {% for product in products %}
        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <img
                  src="{{ product.product.image }}"
                  class="img-fluid rounded-3" alt="Cotton T-shirt">
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">{{ product.product.name }}</p>
                <p><span class="text-muted">{{ product.product.excerpt }}</p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
<select value="{{ product.quantity }}" data-id="{{ product.id }}" class="inputquantity" min="0">
    {% for i in 1..product.product.quantity %}
    {% if i != product.quantity %}
    <option value="{{ i }}">{{i}}</option>
    {% else %}
    <option value="{{ i }}" selected="selected">{{i}}</option>
    {% endif %}
    {% endfor %}
    </select>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">${{ product.product.price * product.quantity }}</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                {{ include('content/_delete_cartproduct_form.html.twig') }}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        <div class="card">
          <div class="card-body">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-6 col-lg-6 col-xl-6">
                <h5 class="mb-0">Total</h5>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-6 text-end">
                <h5 class="mb-0">${{ totalPrice }}</h5>
              </div>
            </div>
            <a href="{{ path('app_profile_checkout', { 'id': app.user.id, 'total': totalPrice }) }}"><button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button></a>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block javascript %}
{{
  parent()
}}
<script scr="{{ asset('./cart.js') }}"></script>
{% endblock %}

templates/content/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ContentController!
{% endblock %}

{% block body %}
	<div
		class="wrapper" style="background-color: #eee;">
		<!-- content here -->
		<br>
		<h1 class="text-center"> Top 3 of Best Seller Product </h1>
		<div class="product-grid product-grid--flexbox" >
			<div
				class="product-grid__wrapper">
				<!-- Product list start here -->

				{% for product in products %}
					<div class="product-grid__product-wrapper">
						<div class="product-grid__product">
							<div class="product-grid__img-wrapper">
								<img src="{{ product.image }}" alt="Img" class="product-grid__img"/>
							</div>
							<span class="product-grid__title">{{ product.name }}</span>
							<span class="product-grid__price">{{ product.price }}$</span>
							<div class="d-flex mt-2">
								{% if product.category.name is defined %}
									<div>
										<span class="badge bg-danger">{{ product.category.name }}</span>
									</div>
								{% endif %}
								{% if product.brand.name is defined %}
									<div class="mx-2">
										<span class="badge bg-danger">{{ product.brand.name }}</span>
									</div>
								{% endif %}
							{% if product.statut == 1 %}
								<div>
									<span class="badge bg-dark"><i class="fa-solid fa-circle-xmark" style="color: white;"></i> Unavailable</span>
								</div>
							{% endif %}
							{% if product.statut == 2 %}
								<div class="mx-2">
									<span class="badge bg-success"><i class="fa-solid fa-circle-check" style="color: white;"></i> Available</span>
								</div>
							{% endif %}
							</div>
							<div class="product-grid__extend-wrapper">
								<div class="product-grid__extend">
									<p class="product-grid__description">{{ product.excerpt }}</p>
									<a href="{{ path('app_product_add', {'id': product.id}) }}">
										<span class="product-grid__btn product-grid__add-to-cart">
											<i class="fa fa-cart-arrow-down"></i>
											Add to cart</span>
									</a>
									<span class="product-grid__btn product-grid__add-to-fav">
										<i class="fa-solid fa-heart"></i>
										Fav</span>
									<a style="color: white;" class="addcartlogo" href="{{ path('app_product_read', {'id': product.id}) }}">
										<span class="product-grid__btn product-grid__view">
											<i class="fa fa-eye"></i>
											View more</span>
									</a>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	<h1 class="text-center"> Nike Products </h1>
		<div class="product-grid product-grid--flexbox" >
			<div
				class="product-grid__wrapper">
				<!-- Product list start here -->

				{% for product in productz %}
					<div class="product-grid__product-wrapper">
						<div class="product-grid__product">
							<div class="product-grid__img-wrapper">
								<img src="{{ product.image }}" alt="Img" class="product-grid__img"/>
							</div>
							<span class="product-grid__title">{{ product.name }}</span>
							<span class="product-grid__price">{{ product.price }}$</span>
							<div class="d-flex mt-2">
								{% if product.category.name is defined %}
									<div>
										<span class="badge bg-danger">{{ product.category.name }}</span>
									</div>
								{% endif %}
								{% if product.brand.name is defined %}
									<div class="mx-2">
										<span class="badge bg-danger">{{ product.brand.name }}</span>
									</div>
								{% endif %}
							{% if product.statut == 1 %}
								<div>
									<span class="badge bg-dark"><i class="fa-solid fa-circle-xmark" style="color: white;"></i> Unavailable</span>
								</div>
							{% endif %}
							{% if product.statut == 2 %}
								<div class="mx-2">
									<span class="badge bg-success"><i class="fa-solid fa-circle-check" style="color: white;"></i> Available</span>
								</div>
							{% endif %}
							</div>
							<div class="product-grid__extend-wrapper">
								<div class="product-grid__extend">
									<p class="product-grid__description">{{ product.excerpt }}</p>
									<a href="{{ path('app_product_add', {'id': product.id}) }}">
										<span class="product-grid__btn product-grid__add-to-cart">
											<i class="fa fa-cart-arrow-down"></i>
											Add to cart</span>
									</a>
									<span class="product-grid__btn product-grid__add-to-fav">
										<i class="fa-solid fa-heart"></i>
										Fav</span>
									<a style="color: white;" class="addcartlogo" href="{{ path('app_product_read', {'id': product.id}) }}">
										<span class="product-grid__btn product-grid__view">
											<i class="fa fa-eye"></i>
											View more</span>
									</a>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
</div>{% endblock %}

templates/content/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ContentController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/user/Dropbox/PC/Desktop/BACHELOR/W3/site-ecommerce-tp/symfony-ecommerce-tp/src/Controller/ContentController.php'|file_link(0) }}">src/Controller/ContentController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/user/Dropbox/PC/Desktop/BACHELOR/W3/site-ecommerce-tp/symfony-ecommerce-tp/templates/content/index.html.twig'|file_link(0) }}">templates/content/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/content/paginator.html.twig
{#
/**
 * @file
 * Bootstrap v5 Sliding pagination control implementation.
 *
 * View that can be used with the pagination module
 * from the Bootstrap CSS Framework
 * https://getbootstrap.com/docs/5.0/components/pagination/
 */
#}
{% extends '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' %}

templates/content/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ContentController!{% endblock %}

{% block body %}
  <section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="{{ app.user.image }}" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            <h5 class="my-3">{{ app.user.firstname}} {{ app.user.lastname }}</h5>
            <p class="text-muted mb-1">Number : {{ app.user.phonenumber }}</p>
            <p class="text-muted mb-4">Address : {{ app.user.address }} </p>
            <div class="d-flex justify-content-center mb-2">
              <button class="btn btn-primary"> <a href="{{ path('app_user_profile_edit', { 'id': app.user.id }) }}" style="color: black;">Edit Profile</a></button>
              <a href="{{ path('app_product_create_profile', { 'id': app.user.id }) }}"><button class="btn btn-outline-primary ms-1">Add Article</button></a>
              {{ include('user_crud/_delete_profile.html.twig') }}
                          <a class="btn btn-outline-primary ms-1" href="{{ path('app_forgot_password_request')}}" style="color: black;">Reset Password</a>
            </div>
          </div>
        </div>
        </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ app.user.firstname }} {{ app.user.lastname }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ app.user.email }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Phone</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ app.user.phonenumber }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ app.user.address }}</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
        {% for product in products %}
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0" style="height: 1090px;">
              <div class="card-body">
                <image src="{{ product.image }}" width="100%" height="20%"></image>
                <p class="mb-1" style="font-size: .77rem; padding-top: 10px;">Name :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.name }}</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Price :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.price }}$</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Excerpt :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.excerpt }}</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Description :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.description }}</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Name :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.name }}</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Quanity :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.quantity }}</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Statut :</p>
                <div class="col-sm-9">
                {% if product.statut == 1 %}
                  <p class="text-muted mb-0">Available</p>
                {% else %}
                 <p class="text-muted mb-0">Unavailable</p>
                {% endif %}
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Sold :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.sold }}</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Brand :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.brand.name }}</p>
                </div>
                <hr>
                <p class="mb-1" style="font-size: .77rem;">Categories :</p>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ product.category.name }}</p>
                </div>
                <hr>
                <div class="text-center">
                <a href="{{ path('app_product_update', {'id': product.id}) }}" class="btn btn-danger">Edit</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          <div class="navigation">
    {{ knp_pagination_render(products, "content/_paginator.html.twig") }}
</div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/content/shop.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ContentController!{% endblock %}

{% block body %}
<div class="wrapper" style="background-color: #eee;">
		<div class="product-grid product-grid--flexbox">
			<div class="product-grid__wrapper">
				{% for product in products %}
				<div class="product-grid__product-wrapper">
						<div class="product-grid__product">
							<div class="product-grid__img-wrapper">
								<img src="{{ product.image }}" alt="Img" class="product-grid__img"/>
							</div>
							<span class="product-grid__title">{{ product.name }}</span>
							<span class="product-grid__price">{{ product.price }}$</span>
							<div class="d-flex mt-2">
								{% if product.category.name is defined %}
									<div>
										<span class="badge bg-danger">{{ product.category.name }}</span>
									</div>
								{% endif %}
								{% if product.brand.name is defined %}
									<div class="mx-2">
										<span class="badge bg-danger">{{ product.brand.name }}</span>
									</div>
								{% endif %}
							{% if product.statut == 1 %}
								<div>
									<span class="badge bg-dark"><i class="fa-solid fa-circle-xmark" style="color: white;"></i> Unavailable</span>
								</div>
							{% endif %}
							{% if product.statut == 2 %}
								<div class="mx-2">
									<span class="badge bg-success"><i class="fa-solid fa-circle-check" style="color: white;"></i> Available</span>
								</div>
							{% endif %}
							</div>
							<div class="product-grid__extend-wrapper">
								<div class="product-grid__extend">
									<p class="product-grid__description">{{ product.excerpt }}</p>
									<a href="{{ path('app_product_add', {'id': product.id}) }}">
										<span class="product-grid__btn product-grid__add-to-cart">
											<i class="fa fa-cart-arrow-down"></i>
											Add to cart</span>
									</a>
									<span class="product-grid__btn product-grid__add-to-fav">
										<i class="fa-solid fa-heart"></i>
										Fav</span>
									<a style="color: white;" class="addcartlogo" href="{{ path('app_product_read', {'id': product.id}) }}">
										<span class="product-grid__btn product-grid__view">
											<i class="fa fa-eye"></i>
											View more</span>
									</a>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
<div class="navigation">
    {{ knp_pagination_render(products, "content/_paginator.html.twig") }}
</div>
{% endblock %}